# STARTING WITH R

"Alright Jeff, that's enough show me how to code in R NOW!" Woah woah easy
tiger. So before we can start working with R, we will have to install it. 

Now remember. We will install the statistical language R, and we will install
another application called RStudio. "Studio? Are we going to produce beats
now?" No. RStudio is an IDE, short for Integrated Development Environment.

Why is an IDE important. It will give us a lot of features and make the coding
experience more pleasant to work with. YOu can create projects and have your
code, any datasets you might want to import or export, all your code objects in
one place. This helps with file management issues as well as makes


## Downloading R & RStudio
You can download R 
- [For Windows](https://cran.r-project.org/bin/windows/base/)
- [For macOS](https://cloud.r-project.org/bin/macosx/)

If you like suffering and use a Linux system (Debian, Fedora/Redhat, Ubuntu),
you can download R [here](https://cran.r-project.org/bin/linux/)


You can then download RStudio [here](https://posit.co/download/rstudio-desktop/). Scroll down and select your operating system and download and install it.


## Creating Our First R Project

In the top right of your screen, you should see a R in a blue box and Project set to None. Click on it, select `New Project` then select `New Directory` then `New Project` and name the project whatever you want to name it and then specify an appropriate location for your project folder on your computer and voila! You have created your first R project!

Coding in RSTudio without a project can get really tedious and you would have to manually be specifying file paths and dealing with location issues. It is recommended that for each project you embark on, you can create a new project for that so you have everything in a central place and can work from there.


So in RStudio, you should see 3 panes on your screen right now. You are probably daydreaming that you are ggoing to be a super developer and write one million lines of code and have everything in the different panes moving to make you seem like you are the guy. WAKE UP, pal!

No seriously so the 3 panes we have now in RStudio, the one on the left is your console, where every R code you type should run. the two ti your right are tabbed just like console but the one on top contains your most important part, your environment. Every object your code creates will be stored here. You can explore the other tabs to familiarize yourself with the application but if you do not want to be overwhelmed, let us move to the last tab. That contains your files, every plot or chart your code creates will be printed to the plots tab and you can view packages you have installed in the packages tab. We wouldn't really need to go into the other tabs now as I am late for a date while writing this... just kidding

[](files/img/programmer_gf.jpeg)

In all honesty, I will not delve into other parts as I want to keep this short and simple so we build from there.

So the console is where you can run your R code one line at a time, you can actually type in the console. Type your first name, wrapped in double quotes in the console in RStudio right now! If you are like me and you are called Jeff, you can type in that and wrap double quotes around it like this: "Jeff".

[](files/img/gifs/glass.gif)

WOW, you beautiful fucking stack of sunshine you wrote your first line of code in R!

So we see first hand that in the console, code only gets run line by line. Enter the R Script! Think of an R Script as your text editor. You can write your program in as many lines of code you want and run it and the output will be run in the console. But where is your R Script you ask me? If you use WIndows, you can use Ctrl + Shift + N to open a new script or if you enjoy pain and want to do everything manually, Go to File in the top left of your RStudio window and select New File and then click on R Script and you're there!





In this lesson we have downloaded and installed R and RStudio and familiarized ourselves with what Rstudio looks like and what the different panes do. We also created a new R Script where we can write R code.




